// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX; import com.ctre.phoenix.motorcontrol.NeutralMode;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DriveTrain extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private WPI_TalonFX rightDriveMotor;
private WPI_TalonFX leftDriveMotor;
private DifferentialDrive differentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public DriveTrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
rightDriveMotor = new WPI_TalonFX(0);
 
    /* Factory default hardware to prevent unexpected behavior */
rightDriveMotor.configFactoryDefault();

        /* Invert Motor? and set Break Mode */
rightDriveMotor.setInverted(false);
rightDriveMotor.setNeutralMode(NeutralMode.Coast);

        /* Set the peak and nominal outputs */
rightDriveMotor.configNominalOutputForward(0, 30);
rightDriveMotor.configNominalOutputReverse(0, 30);
rightDriveMotor.configPeakOutputForward(1, 30);
rightDriveMotor.configPeakOutputReverse(-1, 30);
        


leftDriveMotor = new WPI_TalonFX(2);
 
    /* Factory default hardware to prevent unexpected behavior */
leftDriveMotor.configFactoryDefault();

        /* Invert Motor? and set Break Mode */
leftDriveMotor.setInverted(false);
leftDriveMotor.setNeutralMode(NeutralMode.Coast);

        /* Set the peak and nominal outputs */
leftDriveMotor.configNominalOutputForward(0, 30);
leftDriveMotor.configNominalOutputReverse(0, 30);
leftDriveMotor.configPeakOutputForward(1, 30);
leftDriveMotor.configPeakOutputReverse(-1, 30);
        


differentialDrive = new DifferentialDrive(rightDriveMotor, leftDriveMotor);
 addChild("DifferentialDrive",differentialDrive);
 differentialDrive.setSafetyEnabled(true);
differentialDrive.setExpiration(0.1);
differentialDrive.setMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

